app:
  baseUrl: ${APP_BASE_URL}

backend:
  baseUrl: ${BACKEND_BASE_URL}
  listen:
    port: ${PORT:7007}
    host: ${HOST:0.0.0.0}
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    upgrade-insecure-requests: false

  cors:
    origin: ${APP_BASE_URL}
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true

  auth:
    dangerouslyDisableDefaultAuthPolicy: true
    keys:
      - secret: ${BACKEND_SECRET}

  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT:5432}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      database: ${POSTGRES_DATABASE:postgres}
      ssl:
        rejectUnauthorized: false

# Production Authentication Configuration
auth:
  providers:
    guest:
      dangerouslyAllow: true

catalog:
  locations:
    - type: file
      target: ./examples/entities.yaml
    - type: file
      target: ./examples/template/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ./examples/org.yaml
      rules:
        - allow: [User, Group]
