# Single-stage Dockerfile for Backstage backend (build outside Docker).
# Assumes `yarn build:backend` has been executed prior to `docker build`.

FROM node:24-trixie-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends libsqlite3-dev python3 g++ make && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /app && chown -R node:node /app
WORKDIR /app
USER node

# Copy yarn and root workspace files needed for yarn workspaces focus
COPY --chown=node:node .yarn ./.yarn
COPY --chown=node:node .yarnrc.yml ./
COPY --chown=node:node backstage.json ./
COPY --chown=node:node package.json yarn.lock ./

# Copy pre-built backend skeleton archive (generated by `yarn build:backend`)
COPY --chown=node:node packages/backend/dist/skeleton.tar.gz ./
RUN tar xzf skeleton.tar.gz && rm skeleton.tar.gz

ENV NODE_ENV=production
RUN yarn workspaces focus --all --production && rm -rf "$(yarn cache clean)"

# Copy pre-built backend release bundle (generated by `yarn build:backend`)
COPY --chown=node:node packages/backend/dist/bundle.tar.gz ./
RUN tar xzf bundle.tar.gz && rm bundle.tar.gz

# Copy application configuration files and catalog examples
COPY --chown=node:node examples ./examples
COPY --chown=node:node app-config*.yaml ./

CMD ["node", "packages/backend", "--config", "app-config.yaml", "--config", "app-config.production.yaml"]

