apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: backstage-production
  region: ap-south-1
  version: "1.30"

# Multi-AZ across 3 Availability Zones
availabilityZones:
  - ap-south-1a
  - ap-south-1b
  - ap-south-1c

vpc:
  cidr: "10.30.0.0/16"
  nat:
    gateway: HighlyAvailable # 1 NAT Gateway per AZ for true 99.99% multi-AZ resilience

managedNodeGroups:
  - name: backstage-workers-multi-az
    instanceType: t3.large
    minSize: 3
    maxSize: 6
    desiredCapacity: 3
    privateNetworking: true
    volumeSize: 50
    volumeType: gp3
    availabilityZones:
      - ap-south-1a
      - ap-south-1b
      - ap-south-1c
    labels:
      role: backstage-worker
      environment: production
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/backstage-production: "owned"
    iam:
      withAddonPolicies:
        ebs: true             # Required for PostgreSQL persistent volume (EBS CSI Driver)
        albIngress: true      # Required for AWS Application Load Balancer
        cloudWatch: true      # Required for Container Insights & log streaming
        autoScaler: true      # Required for Cluster Autoscaler

# Core Addons for EKS Production
addons:
  - name: aws-ebs-csi-driver
    wellKnownPolicies:
      ebsCSIController: true
  - name: vpc-cni
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  - name: kube-proxy
  - name: coredns
